version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.0
    - 4.0.0
  - dependency-name: decorator
    versions:
    - 5.0.5
    - 5.0.6
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    timezone: UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: python
    versions:
    - 3.9.3.pre.slim.pre.buster
